### PR TITLE
SCRAM prototype (do not merge yet)

### PR DESCRIPTION
**Pull request by dmlloyd**
This is a prototype of the SCRAM SASL mechanism.  For now it is client only, and there are a few problems, but I want to get initial feedback.

### CODE REVIEW

**Comment by darranl** [comment]
I know interoperability tests with other implementations have been considered although maybe not with a suitable solution found yet!  We probably do as a bare minimum want a base set of tests to verify our own implementation is interoperable with itself!

I have adjusted the roadmap of JBoss SASL so the master branch is heading for a 2.0.0.Alpha1 release so no issue getting the more experimental code incorporated, there is a 1.0.x branch reserved for ongoing maintenance.

**Comment by dmlloyd** [comment]
OK I've re-sorted the commits as discussed.  How does this look?

**Comment by darranl** [comment]
I am going to pull in your first 4 commits, that will just leave us with the mechanism to add.

**Comment by darranl** [comment]
Should we close this one for now, them re-submit when you are ready for the mechanism to be looked at again?

**Comment by darranl** [comment]
Closing, David will resubmit.

**Pull request closed without merging**
